### ISSUE TITLE
Connect plugin template to running the script file

### ISSUE THREAD

**Issue by shafferz** [inTestiGator/pytest-focus#13]
# Description of the Issue

We have a simple script to place the user into the restricted shell environment for bash terminals. We do not, however, have a way to connect this script file to the plugin itself yet. We need to find a way to run the script from the pytest-focus plugin.

## Add Detailed Comment with More Information

This is the first major learning curve of the assignment. Once we figure out how to execute the script, we should be able to demonstrate a working prototype of the pytest-focus plugin.

We will likely use the `os` module of Python to execute the script, as described in the `README.md` file. It would be nice to figure out if we can check that the script has been run in the past, or if we can run the script as part of installing `pytest-focus` so that we can make calling the script easier. This may be inadvisable, though, as we might not want to install a shell script on the user's computer as part of the plugin itself.

### Assigned Developers

@shafferz @baldeosinghm @ilikerustoo @Alex-Yarkosky @yeej2

**Comment by yeej2** [comment]
I can help to figure this out @shafferz.

**Comment by shafferz** [comment]
We are moving in a different direction, without the use of scripts, and as such this is no longer necessary.
