### ISSUE TITLE
Operating System Independent Push-Notifications 

### ISSUE THREAD

**Issue by shafferz** [inTestiGator/pytest-focus#20]
# Description of the Issue
We need to find a way to send push notifications to the user's desktop when they fail a test case. 

## Add Detailed Comment with More Information

For Ubuntu: We can use the `notify-send` command from the terminal (or through Python's access to the terminal) and create notifications this way.

For MacOS: https://stackoverflow.com/questions/17651017/python-post-osx-notification

For Windows 10: https://github.com/jithurjacob/Windows-10-Toast-Notifications

### Assigned Developers

@yeej2 @ilikerustoo @baldeosinghm @Alex-Yarkosky

**Comment by baldeosinghm** [comment]
I have macOS notifications working at the moment. I will look at `instafail` l to see how failed test cases can trigger a push notifications.

instafail link - https://github.com/pytest-dev/pytest-instafail

**Comment by shafferz** [comment]
This issue is deprecated by previous pull requests, as the `pytest-focus` plugin supports push notifications on Mac, Windows, and Linux.
