### ISSUE TITLE
No way to track code coverage

### ISSUE THREAD

**Issue by Alex-Yarkosky** [inTestiGator/pytest-focus#4]
As we begin to add code to the repository, we must consider how we will track the coverage of it by test cases so that we may have 100% or as much as possible covered. I believe that [codecov.io](https://codecov.io/) will work best for doing this.

**Comment by baldeosinghm** [comment]
I have already added a codecov yaml file.  All that is left is for @ilikerustoo to configure Travis CI.

**Comment by Michionlion** [comment]
Travis CI is enabled -- all that is needed is a `.travis.yml` file; you will need to get a codecov token as well, most likely. We may need to coordinate with @gkapfham to get one for the organization; I'm not familiar with the procedure.

**Comment by baldeosinghm** [comment]
I was able to get a codecov token thanks to @sutterj; I believe it works for the organization as well. I recently slacked it to @ilikerustoo.

**Comment by Alex-Yarkosky** [comment]
#15 closed this
